services:
  photo-frame-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_FORWARD_TO_ID=${TELEGRAM_FORWARD_TO_ID}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
